services:
  acontext-server-clickhouse:
    image: clickhouse/clickhouse-server:25.4
    restart: unless-stopped
    container_name: acontext-server-clickhouse
    ports:
      - '${CLICKHOUSE_EXPORT_PORT}:8123'  # HTTP interface (was 18123)
      # - '9000:9000'  # Native client interface
    volumes:
      - ${CLICKHOUSE_LOCATION}:/var/lib/clickhouse
      # - ${CLICKHOUSE_LOGS_LOCATION}:/var/log/clickhouse-server  # Optional: for logs
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      # - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1  # Enable user management
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  acontext-server-pg:
    image: postgres:16
    restart: unless-stopped
    container_name: acontext-server-pg
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '${DATABASE_EXPORT_PORT}:5432'
    volumes:
      - ${DATABASE_LOCATION}:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
  
  acontext-server-redis:
    image: redis:7.4
    restart: unless-stopped
    container_name: acontext-server-redis
    ports:
      - "${REDIS_EXPORT_PORT}:6379"
    volumes:
      - ${REDIS_LOCATION}:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  acontext-server-pg:
    driver: local
  acontext-server-redis:
    driver: local