{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aconext.api.name" . }}
  labels:
    {{- include "aconext.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "aconext.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aconext.api.selectorLabels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aconext.api.serviceAccountName" . }}
      {{- with .Values.api.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          env:
            - name: API_EXPORT_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aconext.api.name" . }}-config
                  key: API_EXPORT_PORT
            {{- if .Values.secrets.api.rootBearerToken }}
            - name: ROOT_API_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "aconext.api.name" . }}-secret
                  key: ROOT_API_BEARER_TOKEN
            {{- end }}
            - name: DATABASE_HOST
              value: {{ include "aconext.postgresql.host" . | quote }}
            - name: DATABASE_EXPORT_PORT
              value: {{ include "aconext.postgresql.port" . | quote }}
            - name: DATABASE_USER
              value: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.username }}{{ else }}{{ .Values.external.postgresql.username }}{{ end | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            {{- else }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aconext.fullname" . }}-postgresql-secret
                  key: password
            {{- end }}
            - name: DATABASE_NAME
              value: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.database }}{{ else }}{{ .Values.external.postgresql.database }}{{ end | quote }}
            - name: REDIS_HOST
              value: {{ include "aconext.redis.host" . | quote }}
            - name: REDIS_EXPORT_PORT
              value: {{ include "aconext.redis.port" . | quote }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
            {{- else if .Values.secrets.redis.password }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aconext.fullname" . }}-redis-secret
                  key: password
            {{- end }}
            - name: RABBITMQ_HOST
              value: {{ include "aconext.rabbitmq.host" . | quote }}
            - name: RABBITMQ_EXPORT_PORT
              value: {{ include "aconext.rabbitmq.port" . | quote }}
            - name: RABBITMQ_USER
              value: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.auth.username }}{{ else }}{{ .Values.external.rabbitmq.username }}{{ end | quote }}
            {{- if .Values.rabbitmq.enabled }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.auth.password | quote }}
            {{- else }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aconext.fullname" . }}-rabbitmq-secret
                  key: password
            {{- end }}
            - name: RABBITMQ_VHOST
              value: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.auth.vhost | default "/" }}{{ else }}{{ .Values.external.rabbitmq.vhost | default "/" }}{{ end | quote }}
            - name: RABBITMQ_VHOST_ENCODED
              value: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.auth.vhost | default "/" | urlquery }}{{ else }}{{ .Values.external.rabbitmq.vhost | default "/" | urlquery }}{{ end | quote }}
            {{- if .Values.api.env.S3_ENDPOINT }}
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aconext.api.name" . }}-config
                  key: S3_ENDPOINT
            {{- end }}
            {{- if .Values.api.env.S3_INTERNAL_ENDPOINT }}
            - name: S3_INTERNAL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aconext.api.name" . }}-config
                  key: S3_INTERNAL_ENDPOINT
            {{- else if .Values.api.env.S3_ENDPOINT }}
            - name: S3_INTERNAL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aconext.api.name" . }}-config
                  key: S3_ENDPOINT
            {{- end }}
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aconext.api.name" . }}-config
                  key: S3_REGION
            {{- if .Values.secrets.s3.accessKey }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "aconext.fullname" . }}-s3-secret
                  key: S3_ACCESS_KEY
            {{- end }}
            {{- if .Values.secrets.s3.secretKey }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "aconext.fullname" . }}-s3-secret
                  key: S3_SECRET_KEY
            {{- end }}
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aconext.api.name" . }}-config
                  key: S3_BUCKET
            - name: CORE_BASE_URL
              value: http://{{ include "aconext.core.name" . }}:{{ .Values.core.service.port }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

