{{- if and .Values.core.enabled .Values.core.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aconext.core.serviceAccountName" . }}
  labels:
    {{- include "aconext.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
  {{- with .Values.core.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.core.serviceAccount.automount }}
{{- end }}

